import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="w-full h-full">
      <Head>
        <title>Goldmand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto p-10 h-screen flex justify-center items-center">
        <h1 className="text-4xl text-red-700">
          Welcome to Goldmand
        </h1>
      </main>
    </div>
  )
}

export default Home
